- name: dockbox
  devices:
    - name: router
      ip: 192.168.0.1
      diagnose:
        name: "Validate {{platform.name}} router availability"
        errorMessage: "An error occur while diagnosing {{platform.name}}"
        actions:
          - name: "Ping {{platform.name}} {{device.name}}"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ping {{device.ip}} -c  5"
- name: auv7
  devices:
    - name: switch
      ip: 192.168.0.10
      diagnose:
        name: "Validate {{platform.name}} {{device.name}} availability"
        errorMessage: "An error occur while diagnosing {{platform.name}} {{device.name}}"
        actions:
          - name: "{{platform.name}} {{device.name}} available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ping {{device.ip}} -c  5"
    - name: computer
      ip: 192.168.0.11
      user: sonia
      usbCamFrontId: 1e10:3300
      usbCamBottomId: 1e10:3300
      usbImuId: 1e10:3300
      usbHydroId: 1e10:3300
      diagnose:
        name: "Validate {{platform.name}} {{device.name}} availability"
        errorMessage: "An error occur while diagnosing {{platform.name}} {{device.name}}"
        actions:
          - name: "{{platform.name}} {{device.name}} available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ping {{device.ip}} -c  5"
          - name: "{{platform.name}} {{device.name}} docker daemon available"
            errorMessage: "{{platform.name}} {{device.name}} docker daemon seems to be unavailable"
            cmd: "docker -H ssh://{{device.user}}@{{device.ip}} ps"
          - name: "{{platform.name}} front-camera available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ssh -o ConnectTimeout=15 {{device.user}}@{{device.ip}} lsusb | grep '{{device.usbCamFrontId}}'"
          - name: "{{platform.name}} bottom-camera available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ssh -o ConnectTimeout=15 {{device.user}}@{{device.ip}} lsusb | grep '{{device.usbCamBottomId}}'"
          - name: "{{platform.name}} imu available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ssh -o ConnectTimeout=15 {{device.user}}@{{device.ip}} lsusb | grep '{{device.usbIMUId}}'"
          - name: "{{platform.name}} hydrophones available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ssh -o ConnectTimeout=15 {{device.user}}@{{device.ip}} lsusb | grep '{{device.usbHydroId}}'"

    - name: dvl
      ip: 192.168.0.12
      diagnose:
        name: "Validate {{platform.name}} {{device.name}} availability"
        errorMessage: "An error occur while diagnosing {{platform.name}} {{device.name}}"
        actions:
          - name: "{{platform.name}} {{device.name}} available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ping {{device.ip}} -c  5"
    - name: sonar
      ip: 192.168.0.50
      diagnose:
        name: "Validate {{platform.name}} {{device.name}} availability"
        errorMessage: "An error occur while diagnosing {{platform.name}} {{device.name}}"
        actions:
          - name: "{{platform.name}} {{device.name}} available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ping {{device.ip}} -c  5"

- name: auv8
  devices:
    - name: switch
      ip: 192.168.0.30
      diagnose:
        name: Validate {{platform.name}} {{device.name}} availability
        errorMessage: "An error occur while diagnosing {{platform.name}} {{device.name}}"
        actions:
          - name: "{{platform.name}} {{device.name}} available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ping {{device.ip}} -c  5"
    - name: computer
      ip: 192.168.0.31
      user: sonia
      usbCamFrontId: 1e10:3300
      usbCamBottomId: 1e10:3300
      usbImuId: 1e10:3300
      usbHydroId: 1e10:3300
      diagnose:
        name: "Validate {{platform.name}} {{device.name}} availability"
        errorMessage: "An error occur while diagnosing {{platform.name}} {{device.name}}"
        actions:
          - name: "{{platform.name}} {{device.name}} available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ping {{device.ip}} -c  5"
          - name: "{{platform.name}} {{device.name}} docker daemon available"
            errorMessage: "{{platform.name}} {{device.name}} docker daemon seems to be unavailable"
            cmd: "docker -H ssh://{{device.user}}@{{device.ip}} ps"
          - name: "{{platform.name}} front-camera available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ssh -o ConnectTimeout=15 {{device.user}}@{{device.ip}} lsusb | grep '{{device.usbCamFrontId}}'"
          - name: "{{platform.name}} bottom-camera available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ssh -o ConnectTimeout=15 {{device.user}}@{{device.ip}} lsusb | grep '{{device.usbCamBottomId}}'"
          - name: "{{platform.name}} imu available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ssh -o ConnectTimeout=15 {{device.user}}@{{device.ip}} lsusb | grep '{{device.usbIMUId}}'"
          - name: "{{platform.name}} hydrophones available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ssh -o ConnectTimeout=15 {{device.user}}@{{device.ip}} lsusb | grep '{{device.usbHydroId}}'"
    - name: dvl
      ip: 192.168.0.32
      diagnose:
        name: "Validate {{platform.name}} {{device.name}} availability"
        errorMessage: "An error occur while diagnosing {{platform.name}} {{device.name}}"
        actions:
          - name: "{{platform.name}} {{device.name}} available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ping {{device.ip}} -c  5"
    - name: sonar
      ip: 192.168.0.50
      diagnose:
        name: Validate {{platform.name}} {{device.name}} availability
        errorMessage: "An error occur while diagnosing {{platform.name}} {{device.name}}"
        actions:
          - name: "{{platform.name}} {{device.name}} available"
            errorMessage: "{{platform.name}} {{device.name}} seems to be unavailable"
            cmd: "ping {{device.ip}} -c  5"
