- name: dockbox
  devices:
    - name: router
      ip: 192.168.0.1
      diagnose:
        name: Checking router
        success_message: "Validation succeded for router"
        error_message: "An error occur while "
        actions:
          - name: "Pinging router"
            success_message: "Router is up"
            error_message: "Router seems to be down..."
            cmd: "ping 192.168.0.1 -n 5"

- name: auv7
  devices:
    - name: switch
      ip: 192.168.0.10
    - name: computer
      ip: 192.168.0.11
    - name: sonar
      ip: 192.168.0.12
- name: auv8
  devices:
    - name: switch
      ip: 192.168.0.30
    - name: computer
      ip: 192.168.0.31
    - name: sonar
      ip: 192.168.0.32