auv7:
  devices:
    computer:
      execute:
        - name: ssh
          cmd: ssh -X {{device.user}}@{{device.ip}}
        - name: shutdown
          cmd: ssh -X {{device.user}}@{{device.ip}} sudo shutdown now
        - name: reboot
          cmd: ssh -X {{device.user}}@{{device.ip}} sudo reboot now

auv8:
  devices:
    computer:
      execute:
        - name: ssh
          cmd: ssh -X {{device.user}}@{{device.ip}}
        - name: shutdown
          cmd: ssh -X {{device.user}}@{{device.ip}} sudo shutdown now
        - name: reboot
          cmd: ssh -X {{device.user}}@{{device.ip}} sudo reboot now