- name: local
  devices:
    - name: computer
      os:
        - name: darwin
          actions:
            # - name: "Update system packages and install git"
            #   errorMessage: "An error occurred while updating system packages"
            #   cmd: "sudo apt update && sudo apt upgrade -y && sudo apt-get install git"
            # - name: "Validate SSH key exist"
            #   errorMessage: "You need to have an ssh key to be able to install environnement see (https://wiki.sonia.etsmtl.ca/e/en/software/architecture/sonia-cli/overview)"
            #   cmd: "[ -f ~/.ssh/id_rsa ]"
            # - name: "Validate github personal token exist"
            #   errorMessage: "You need to have a github personal access token to be able to install environment see (https://wiki.sonia.etsmtl.ca/e/en/software/architecture/sonia-cli/overview)"
            #   cmd: "[ -f ~/TOKEN.txt ]"
            - name: "Copy SSH key into AUV7"
              errorMessage: "An error occurred wile copying SSH key to AUV7"
              cmd: "ssh-copy-id {{auv7.computer.user }}@{{ auv7.computer.ip }}"
            - name: "Copy SSH key into AUV8"
              errorMessage: "An error occurred wile copying SSH key to AUV8"
              cmd: "ssh-copy-id {{auv8.computer.user }}@{{auv8.computer.ip}}"
            # - name: "Installing docker requirements"
            #   errorMessage: "An error occurred while installing docker"
            #   cmd: "sudo apt install apt-transport-https ca-certificates curl software-properties-common"
            # - name: "Adding docker to source repository list"
            #   errorMessage: "An error occurred while adding docker to os repo list"
            #   cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable' && sudo apt update"
            # - name: "Install Docker"
            #   errorMessage: "An error occurred while installing docker"
            #   cmd: "sudo apt install docker-ce && sudo systemctl status docker"
            # - name: "Adding docker group membership to current user"
            #   errorMessage: "An error occurred while adding docker group to current user"
            #   cmd: "sudo usermod -aG docker ${USER} && su - ${USER}"
            # - name: "Install docker-compose"
            #   errorMessage: "An error occurred while installing docker-compose"
            #   cmd: "sudo curl -L 'https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose"
            # - name: "Create docker context for AUV7"
            #   errorMessage: "An error occured while creating docker context for AUV7"
            #   cmd: "docker context --create 'host=ssh://sonia@192.168.0.11'"
            # - name: "Create docker context for AUV8"
            #   errorMessage: "An error occured while creating docker context for AUV7"
            #   cmd: "docker context --create 'host=ssh://sonia@192.168.0.11'"
            # - name: "Login to github packages registry"
            #   errorMessage: "An error occcured while authenticating to github packages registry"
            #   cmd: "cat ~/TOKEN.txt | docker login https://docker.pkg.github.com -u USERNAME --password-stdin"
            # - name: "Add VSCode to source repository list"
            #   errorMessage: "An error message occurred while adding VSCode to source repository list"
            #   cmd: "wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add - && sudo add-apt-repository 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'"
            # - name: "Install VSCode"
            #   errorMessage: "An error occurred while installing vscode"
            #   cmd: "sudo apt update && sudo apt install code -y"
            # - name: "Create Sonia Workspace"
            #   errorMessage: "An error message occurred while creating sonia workspace"
            #   cmd: "mkdir ~/Workspace/src"
            #TODO: Clone repo and pull images

        - name: linux
          actions:
            - name: "Install brew"
              errorMessage: "An error occurred while validating brew is installed or installing brew"
              cmd: brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            - name: "Install git"
              errorMessage: "Install Git"
              cmd: "brew install git"
            - name: "Generate SSH Key"
              errorMessage: "An error occurred while generating an SSH key"
              cmd: "ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y 2>&1 >/dev/null"
            - name: "Copy SSH key to your github profile"
              errorMessage: "An error occurred during this step (press enter completed)"
              cmd: "readline"
            - name: "Install docker"
              errorMessage: "An error occurred while installing docker"
              cmd: "brew cask install docker"
            - name: "Install VSCode"
              errorMessage: "An error occurred while installing"
              cmd: "brew cask install visual-studio-code"
            - name: "Create Sonia Workspace"
              errorMessage: "An error message occurred while creating sonia workspace"
              cmd: "mkdir ~/Workspace/src"

        - name: win32

- name: auv7
  devices:
    - name: computer
      os:
        - name: "linux"
          actions:
            - name: "Update system packages"
              errorMessage: "An error occurred while updating system packages"
              cmd: "sudo apt update && sudo apt upgrade -y"
            - name: "Installing docker requirements"
              errorMessage: "An error occurred while installing docker"
              cmd: "sudo apt install apt-transport-https ca-certificates curl software-properties-common"
            - name: "Adding docker to source repository list"
              errorMessage: "An error occurred while adding docker to os repo list"
              cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable' && sudo apt update"
            - name: "Install Docker"
              errorMessage: "An error occurred while installing docker"
              cmd: "sudo apt install docker-ce && sudo systemctl status docker"
            - name: "Adding docker group membership to current user"
              errorMessage: "An error occurred while adding docker group to current user"
              cmd: "sudo usermod -aG docker ${USER} && su - ${USER}"
            - name: "Install docker-compose"
              errorMessage: "An error occurred while installing docker-compose"
            - name: "Docker login"
              errorMessage: "An error occurred while login to github docker repository"
              cmd: ""

- name: auv8
  devices:
    - name: computer
      os:
        - name: "linux"
          actions:
            - name: "Update system packages"
              errorMessage: "An error occurred while updating system packages"
              cmd: "sudo apt update && sudo apt upgrade -y"
            - name: "Installing docker requirements"
              errorMessage: "An error occurred while installing docker"
              cmd: "sudo apt install apt-transport-https ca-certificates curl software-properties-common"
            - name: "Adding docker to source repository list"
              errorMessage: "An error occurred while adding docker to os repo list"
              cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable' && sudo apt update"
            - name: "Install Docker"
              errorMessage: "An error occurred while installing docker"
              cmd: "sudo apt install docker-ce && sudo systemctl status docker"
            - name: "Adding docker group membership to current user"
              errorMessage: "An error occurred while adding docker group to current user"
              cmd: "sudo usermod -aG docker ${USER} && su - ${USER}"
            - name: "Install docker-compose"
              errorMessage: "An error occurred while installing docker-compose"
            - name: "Docker login"
              errorMessage: "An error occurred while login to github docker repository"
              cmd: ""
