- name: "flexbe_app"
  url: "git@github.com:FlexBE/flexbe_app.git"
- name: "controller_mission"
  url: "git@github.com:sonia-auv/controller_mission"
- name: "lib_atlas"
  url: "git@github.com:sonia-auv/lib_atlas"
- name: "provider_imu"
  url: "git@github.com:sonia-auv/provider_imu"
- name: "provider_imu"
  url: "git@github.com:sonia-auv/provider_imu"
- name: "provider_dvl"
  url: "git@github.com:sonia-auv/provider_dvl"
- name: "provider_sonar"
  url: "git@github.com:sonia-auv/provider_sonar"
- name: "provider_vision"
  url: "git@github.com:sonia-auv/provider_vision"
- name: "provider_thruster"
  url: "git@github.com:sonia-auv/provider_thruster"
- name: "provider_keypad"
  url: "git@github.com:sonia-auv/provider_keypad"
- name: "provider_kill_mission"
  url: "git@github.com:sonia-auv/provider_kill_mission"
- name: "provider_power"
  url: "git@github.com:sonia-auv/provider_power"
- name: "provider_system"
  url: "git@github.com:sonia-auv/provider_system"
- name: "provider_hydrophone"
  url: "git@github.com:sonia-auv/provider_hydrophone"
- name: "provider_actuators"
  url: "git@github.com:sonia-auv/provider_actuators"
- name: "proc_hydrophone"
  url: "git@github.com:sonia-auv/proc_hydrophone"
- name: "proc_actuators"
  url: "git@github.com:sonia-auv/proc_actuators"
- name: "deep_detector"
  url: "git@github.com:sonia-auv/deep_detector"
- name: "proc_mapping"
  url: "git@github.com:sonia-auv/proc_mapping"
- name: "proc_navigation"
  url: "git@github.com:sonia-auv/proc_navigation"
- name: "proc_control"
  url: "git@github.com:sonia-auv/proc_control"
- name: "proc_sonar"
  url: "git@github.com:sonia-auv/proc_sonar"
- name: "proc_image_processing"
  url: "git@github.com:sonia-auv/proc_image_processing"
- name: "sonia_messages"
  url: "git@github.com:sonia-auv/sonia_messages"
- name: "tcp_serial_redirect"
  url: "git@github.com:sonia-auv/tcp_serial_redirect"
- name: "proc_navigation"
  url: "git@github.com:sonia-auv/proc_navigation"
- name: "interface_RS485"
  url: "git@github.com:sonia-auv/interface_RS485"
- name: "control_library"
  url: "git@github.com:sonia-auv/control_library"
