name: Unit Test And Deploy - Master Branch

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-npm:
    name: "Publish to NPM"
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    name: "Create Github Release"
    runs-on: ubuntu-latest
    needs: [build-and-test, publish-npm]
    steps:
      - uses: actions/checkout@v2
      - name: Set Target Version
        run: echo "TARGET_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')" >> $GITHUB_ENV
      - name: Create Git Tag
        run: |
          git tag ${TARGET_VERSION}
          git push origin --tags

      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TARGET_VERSION }}
          release_name: Release ${{ env.TARGET_VERSION }}
          body: |
            A new release for this package has been created
          draft: false
          prerelease: false
